/**
 * File: bootAnim.cpp
 *
 * Author: Al Chaussee
 * Created: 07/27/2018
 *
 * Description: Draws the boot animation to the screen forever until stopped
 *              Leaves the screen on when stopped under the assumption whatever is stopping
 *              it will continue to use the screen
 *
 * Copyright: Lrya, Inc. 2018
 *
 **/

#include "core/lcd.h"

#include <stdio.h>
#include <fcntl.h>
#include <sys/mman.h>
#include <unistd.h>
#include <chrono>
#include <algorithm>
#include <signal.h>

// #define FRAME_WIDTH_SANTEK  184 
// #define FRAME_HEIGHT_SANTEK 96
// #define FRAME_WIDTH_MIDAS 160
// #define FRAME_HEIGHT_MIDAS 80
#define FRAME_WIDTH_IPS 240
#define FRAME_HEIGHT_IPS 240
// #define NUM_BYTES_PER_FRAME_SANTEK (FRAME_WIDTH_SANTEK * FRAME_HEIGHT_SANTEK * sizeof(uint16_t))
// #define NUM_BYTES_PER_FRAME_MIDAS (FRAME_WIDTH_MIDAS * FRAME_HEIGHT_MIDAS * sizeof(uint16_t))
#define NUM_BYTES_PER_FRAME_IPS (FRAME_WIDTH_IPS * FRAME_HEIGHT_IPS * sizeof(uint16_t))

namespace {
  // Path to the boot animation file generated by `python3 /robot/test/gif_to_raw.py <gif of boot animation>`
  // It is a binary file containing all the frames in the animation in rgb565 format
  static const char* _animPathSantek = "/lrya/data/assets/cozmo_resources/config/engine/animations/boot_anim.raw";
//   static const char* _animPathMidas = "/lrya/data/assets/cozmo_resources/config/engine/animations/boot_anim_20.raw";
  bool gShutdown = false;
}

extern "C" void core_common_on_exit(void)
{
  lcd_shutdown();
}

bool use_santek_sizes() {
//   return lcd_display_version() == SANTEK;
  return true;
}

static void animate(void* frame)
{
//   if (use_santek_sizes()) {
//     lcd_draw_frame2((uint16_t*)frame, FRAME_WIDTH_SANTEK * FRAME_HEIGHT_SANTEK * sizeof(uint16_t));
//   } else {
//     lcd_draw_frame2((uint16_t*)frame, FRAME_WIDTH_MIDAS * FRAME_HEIGHT_MIDAS * sizeof(uint16_t));
//   };
    lcd_draw_frame2((uint16_t*)frame, FRAME_WIDTH_IPS * FRAME_HEIGHT_IPS * sizeof(uint16_t));
}

static void handler(int signum)
{
  gShutdown = true;
}

int main(int argc, char** argv)
{
  printf("0.in bootAnim...\n");fflush(stdout);
  // Setup signal handlers so we can cleanly exit
  printf("0.1.signal(SIGTERM,  handler)\n");
  signal(SIGTERM, handler);
  printf("0.2.signal(SIGINT,  handler)\n");
  signal(SIGINT,  handler);

  printf("1.start lcd_init...\n");
  lcd_init();
  printf("1.done lcd_init...\n");
  printf("2.start lcd_clear_screen...\n");
  lcd_clear_screen();
  printf("2.done lcd_clear_screen...\n");
  printf("3.start lcd_shutdown...\n");
  lcd_shutdown();
  printf("3.done lcd_shutdown...\n");
  
  // Init lcd
  printf("4.start lcd_init...!\n");
  int rc = lcd_init();
  if (rc != 0)
  {
    printf("Failed to init lcd\n");
    return rc;
  }
  printf("4.init lcd_init ok!\n");

  // Open animation file for reading
//   const char *anim_path = use_santek_sizes() ? _animPathSantek : _animPathMidas;
  const char *anim_path = _animPathSantek;
  printf("5.start open(anim_path, O_RDONLY)\n");
  int fd = open(anim_path, O_RDONLY);
  if(fd < 0)
  {
    printf("Failed to open %s\n", anim_path);
    return -1;
  }
  printf("5.done open(anim_path, O_RDONLY)\n");

  // Get the length of the file to determine how long the animation is
  printf("6.start lseek(fd, 0, SEEK_END)\n");
  off_t len = lseek(fd, 0, SEEK_END);
  if(len == -1)
  {
    printf("lseek failed\n");
    return -1;
  }
  printf("6.done lseek(fd, 0, SEEK_END)\n");
//   static const uint32_t kTotalNumFrames = len / ( use_santek_sizes() ? NUM_BYTES_PER_FRAME_SANTEK : NUM_BYTES_PER_FRAME_MIDAS);
  static const uint32_t kTotalNumFrames = len / (NUM_BYTES_PER_FRAME_IPS);
  printf("7.start mmap(nullptr, len, PROT_READ, MAP_PRIVATE, fd, 0)\n");

  // Memory map the anim file
  void* anim = mmap(nullptr, len, PROT_READ, MAP_PRIVATE, fd, 0);
  if(anim == nullptr)
  {
    printf("mmap failed\n");
    return -1;
  }
  printf("7.done mmap(nullptr, len, PROT_READ, MAP_PRIVATE, fd, 0)\n");

  // Close the fd after memory mapping
  printf("8.start close(fd)\n");
  rc = close(fd);
  if(rc != 0)
  {
    printf("close failed\n");
  }  
  printf("8.done close(fd)\n");

  // Start drawing the boot animation to the screen

  // Keep track of how far in time we are in this loop of the animation
  // since drawing the frame takes longer than the frame should actually
  // be displayed (~41ms to draw vs a desired frame rate of 24fps)
  // we need to skip frames
  uint32_t timeCount = 0;
  printf("9.Start drawing the boot animation to the screen\n");
  
  while (!gShutdown)
  {
//     printf("10.Start while (!gShutdown)\n");
    // Figure out which frame we should play in order to adhere to
    // a frame rate of kFrameDuration_ms
    static const uint32_t kFrameDuration_ms = 41;
    const uint32_t nextFrameToDraw = timeCount / kFrameDuration_ms;

    // Time how long it takes to animate/draw this frame
    const auto startTime = std::chrono::steady_clock::now();

//     const uint32_t frame_offset = use_santek_sizes() ? NUM_BYTES_PER_FRAME_SANTEK : NUM_BYTES_PER_FRAME_MIDAS;
    const uint32_t frame_offset = NUM_BYTES_PER_FRAME_IPS;
//     printf("11.Start animate(((uint8_t*)anim) + (nextFrameToDraw * frame_offset))\n");
    animate(((uint8_t*)anim) + (nextFrameToDraw * frame_offset));
    const auto endTime = std::chrono::steady_clock::now();

    const auto dif = std::chrono::duration_cast<std::chrono::milliseconds>(endTime - startTime);
    timeCount += dif.count();

    // Role timeCount over if it exceeds the total duration of the animation
    if(timeCount >= ((kTotalNumFrames-1)*kFrameDuration_ms))
    {
      timeCount %= kTotalNumFrames * kFrameDuration_ms;
    }
  }
//   printf("12.Start Unmap the anim\n");

  // Unmap the anim
  rc = munmap(anim, len);
  if(rc != 0)
  {
    printf("munmap failed\n");
  }
//   printf("13.Start lcd_shutdown()\n");

  lcd_shutdown();
//   printf("14.done lcd_shutdown()\n");
  return 0;
}

